[build]
  command="ng build"
  publish="dist/portfolio"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


#[[plugins]]
#  package = "netlify-plugin-cypress"
#
#  [plugins.inputs.onSuccess]
#    enable = true
#
#  [plugins.inputs]
#    enable = false